ARCH:=../../architect.py
FASTA:=/home/kuleshov/drosophila/asm/spades-shotgun/out/scaffolds.fasta
TSV:=/home/kuleshov/drosophila/align/spades-shotgun-to-self/besst.edges.tsv

run:
	$(ARCH) scaffold \
	  --fasta $(FASTA) \
	  --edges $(TSV)


